[package]
name = "pallet-im-online"
version = "27.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true
description = "FRAME's I'm online pallet"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { features = ["derive"], workspace = true }
log = { workspace = true }
scale-info = { features = ["derive", "serde"], workspace = true }
frame = { workspace = true, features = ["experimental", "runtime"] }
pallet-authorship = { workspace = true }
sp-staking = { features = ["serde"], workspace = true }

[dev-dependencies]
pallet-session = { workspace = true, default-features = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame/std",
	"log/std",
	"pallet-authorship/std",
	"pallet-session/std",
	"scale-info/std",
	"sp-staking/std",
]
runtime-benchmarks = [
	"frame/runtime-benchmarks",
	"sp-staking/runtime-benchmarks",
]
try-runtime = [
	"frame/try-runtime",
	"pallet-authorship/try-runtime",
	"pallet-session/try-runtime",
]
